#!/bin/bash
#banner
printf '<\>'|lolcat -a -s 99 -d 30
echo ' We Are Hacker
WELCOME TO TERMUX'|lolcat -a -s 99 -d 300

clear

printf '\e[032m▉▉▉▉▉
   ▉▉▉▉▉
      ▉▉▉▉▉
         ▉▉▉▉▉
            ▉▉▉▉▉
               ▉▉▉▉
                ▉▉▉▉▉▶
               ▉▉▉▉
            ▉▉▉▉▉
         ▉▉▉▉▉
      ▉▉▉▉▉              FB: BLACK SHADOW
   ▉▉▉▉▉
▉▉▉▉▉                ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉\n\n'
